name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Runs the Super-Linter action
#      - name: Run Super-Linter
#        uses: github/super-linter@v3
#        env:
#          DEFAULT_BRANCH: main
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      Use checkstyle
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Run check style
#        uses: nikitasavinov/checkstyle-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          reporter: 'github-pr-check'
#          tool_name: 'testtool'
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - name: Build with Gradle
        run: make install
